### ISSUE TITLE
Storing data locally

### ISSUE THREAD

**Issue by Alkahestry** [soruly/anilist-crawler#147]
Hi I don't know nodejs much but I need to crawl data from anilist, I have followed the instruction and decided not to connect to both DB, so I left ES_HOST and DB_HOST blank in .env file. After that I crawled with `node index.js --anime 1` and it said completed, but the data in local file is no where to be found. Maybe you haven't implemented output for local file ? Or it's just somewhere in the sub folder. Thanks in advance!

**Comment by soruly** [comment]
This crawler would only store data in MariaDB / elasticsearch. Do you want it to dump *.json files?

**Comment by Alkahestry** [comment]
Yeah, eventually I managed to connect it to MariaDB smoothly after a few hours of trying. Is it possible to dump *.json files without connecting to any other database ?

**Comment by soruly** [comment]
I've pushed a new version with json file output support. (9735e0a2335b5c54a6010263270f309f10e2fae8)
add `FS_DIR=/you/path` in your .env file and try agin

**Comment by Alkahestry** [comment]
Thank you so much for your response and updating the code! I appreciate it

**Comment by soruly** [comment]
Nope there's no such function to dump as files. I can add this featue when
I'm free tho
